name: '${name}'
version: '${version}'
main: fr.groupez.template.ZTemplate
description: Default plugin description
website: https://groupez.dev
author: Maxlego08
api-version: 1.21
softdepend:
  - PlaceholderAPI
